### ISSUE TITLE
DMARC Record Escaping in OVH Provider for OctoDNS

### ISSUE THREAD

**Issue by K3RM1T-CYBER** [octodns/octodns-ovh#46]
We are experiencing an issue with DMARC TXT record synchronization between our OctoDNS configuration and OVH. Specifically, the ; characters within the DMARC record require escaping (i.e., `\;`) to be accepted by OctoDNS. However, when this escaping is applied, OctoDNS consistently proposes an update during the sync process, indicating that the synchronization is not effective.

1.	In our YAML configuration, the DMARC record is written with escape characters as required:
```
_dmarc:
  - ttl: 3600
    type: TXT
    values:
      - v=DMARC1\; p=none\; sp=none\; rua=mailto:admin@example.com!10m\; ruf=mailto:admin@example.com!10m\; rf=afrf\; pct=100\; ri=86400
```

2.	When running octodns-sync, it proposes an update:
```
* Update
*     <TxtRecord TXT 0, _dmarc.example.com., ['v=DMARC1; p=none; sp=none; rua=mailto:admin@example.com!10m; ruf=mailto:admin@example.com!10m; rf=afrf; pct=100; ri=86400']> ->
*     <TxtRecord TXT 0, _dmarc.example.com., ['v=DMARC1\; p=none\; sp=none\; rua=mailto:admin@example.com!10m\; ruf=mailto:admin@example.com!10m\; rf=afrf\; pct=100\; ri=86400']> (yaml-ovh)
```

We are unsure if the issue is caused by incorrect handling of escaped characters in our YAML configuration or if it is related to how OVH’s API stores and returns TXT records.
Could you please confirm if this is a known issue with OVH’s API or if we are missing something in our OctoDNS configuration?
